---
- hosts: all
  become: yes
  tasks:
      - name: install apache2 and update pakage
        apt:
           name: apache2
           state: present
        notify: 
            - restart and enable apache2
        ignore_errors: true    

      - name: install php modules
        apt:
            name: "{{ item }}"
            state: present
        loop:
            - php
            - php-cli    
        notify: 
            - restart and enable apache2
        ignore_errors: true    

  handlers:
      - name: restart and enabled apache2 
        service:
            name: apache2
            enabled: yes
            state: restarted
