---
- hosts: all
  become: yes
  tasks:
      - name: install httpd and update pakage
        yum:
           name: httpd
           state: present
        notify: 
            - restart and enable httpd

      - name: install php modules
        yum:
            name: "{{ item }}"
            state: present
        loop:
            - php
            - libapache2-mod-php
            - php-mysql
            - php-cli    
        notify: 
            - restart and enable httpd

  handlers:
      - name: restart and enabled httpd 
        service:
            name: httpd
            enabled: yes
            state: restarted
